### ISSUE TITLE
Improve config layout/fields/defaults

### ISSUE THREAD

**Issue by HydrofinLoewenherz** [scrayosnet/xenos#53]

**Comment by scrayos** [comment]
Looking at the current state of the configuration in https://github.com/scrayosnet/xenos/blob/556c48b92d828ddaee241aeb0a558699bc989434/config/default.toml here are my wishes:

I'd prefer the `unsigned_profile` to be `signed_profiles` and default to false. I know you've inherited this from `?unsigned=false` of the Mojang API endpoint, but I'd say that's rather confusing, as I feel like "signing" is something that I'd like to **enable** and not "unsigning" is something that I'd **disable**.

I'd prefer the time format to be more intuitive, if possible. I know we're using the official and exact duration format, but I feel like something like `3d` would be way more readable that `P3D` or `30s` would be more readable than `PT30S`. What are our options here? Are there any established alternatives that we could parse? Is there anything for that in our config crate?

Aside from those two concerns, I'm very happy with all the changes you've already made. We should add a clickable link for the explanation/documentation to the file or (even better) describe the configuration in the default.toml. The explanations should be easily understandable, even without knowing the inner workings of the code.

**Comment by HydrofinLoewenherz** [comment]
We would have to implement something ourself or find a maintained crate that provides that functionality.
