### ISSUE TITLE
Default custom config location is inconvenient on Kubernetes

### ISSUE THREAD

**Issue by scrayos** [scrayosnet/xenos#69]
We're putting our default config in `/config/default` and expect our custom configuration (without any tweaking) at `/config/config`. That is inconvenient since we would mount the config in a config map that always takes an entire directory. Therefore we should change the structure to something like `/config/default/config.toml` and `/config/custom/config.toml`.

**Comment by HydrofinLoewenherz** [comment]
Changing it to two files
- Default: contains default configurations, and gives value to all fields. Location configurable with env `CONFIG_DEFAULT_FILE`, defaulting to `config/default
- Custom: contains custom (local/deployment) configurations, and overwrites defaults. Location configurable with env `CONFIG_CUSTOM_FILE`, defaulting to `config/custom`

Also the default config file is copied to `config/default/default.toml` in the images.

**Comment by scrayos** [comment]
> Changing it to two files
> 
> * Default: contains default configurations, and gives value to all fields. Location configurable with env `CONFIG_DEFAULT_FILE`, defaulting to `config/default
> * Custom: contains custom (local/deployment) configurations, and overwrites defaults. Location configurable with env `CONFIG_CUSTOM_FILE`, defaulting to `config/custom`
> 
> Also the default config file is copied to `config/default/default.toml` in the images.

I think this may add more confusion than it helps. Couldn't we include the defaults into the binary and then just have `CONFIG_FILE`? That's what I'd expect from a user perspective and how many other projects are managed.

**Comment by HydrofinLoewenherz** [comment]
https://github.com/mehcode/config-rs/issues/27
https://doc.rust-lang.org/std/macro.include_str.html
